services:
  caddy:
    image: caddy:2-alpine
    container_name: shared_caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - shared-proxy

configs:
  caddyfile:
    content: |
      ${RENARDEAU_DOMAIN} {
          reverse_proxy renardeau_app:3000
      }

      ${NOISETTE_DOMAIN} {
          reverse_proxy noisette_app:3000
      }

volumes:
  caddy_data:
  caddy_config:

networks:
  shared-proxy:
    external: true
